apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      # Stage Datasources
      - name: Mimir-Stage
        uid: mimir-stage
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 30s
          httpHeaderName1: 'X-Scope-OrgID'
          manageAlerts: true
          prometheusType: Mimir
          prometheusVersion: 2.40.0
        secureJsonData:
          httpHeaderValue1: 'stage'
      
      - name: Loki-Stage
        uid: loki-stage
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          maxLines: 1000
          httpHeaderName1: 'X-Scope-OrgID'
          manageAlerts: true
          derivedFields:
            - datasourceUid: 'tempo-stage'
              matcherRegex: '"traceid":"(\w+)"'
              name: TraceID
              url: '$${__value.raw}'
              urlDisplayLabel: 'View Trace'
        secureJsonData:
          httpHeaderValue1: 'stage'
      
      - name: Tempo-Stage
        uid: tempo-stage
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki-stage'
            filterByTraceID: true
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: 'mimir-stage'
          serviceMap:
            datasourceUid: 'mimir-stage'
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'stage'
      
      # Prod Datasources
      - name: Mimir-Prod
        uid: mimir-prod
        type: prometheus
        access: proxy
        url: http://mimir:9009/prometheus
        editable: true
        jsonData:
          timeInterval: 30s
          httpHeaderName1: 'X-Scope-OrgID'
          manageAlerts: true
          prometheusType: Mimir
          prometheusVersion: 2.40.0
        secureJsonData:
          httpHeaderValue1: 'prod'
      
      - name: Loki-Prod
        uid: loki-prod
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          maxLines: 1000
          httpHeaderName1: 'X-Scope-OrgID'
          manageAlerts: true
          derivedFields:
            - datasourceUid: 'tempo-prod'
              matcherRegex: '"traceid":"(\w+)"'
              name: TraceID
              url: '$${__value.raw}'
              urlDisplayLabel: 'View Trace'
        secureJsonData:
          httpHeaderValue1: 'prod'
      
      - name: Tempo-Prod
        uid: tempo-prod
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki-prod'
            filterByTraceID: true
            filterBySpanID: false
          tracesToMetrics:
            datasourceUid: 'mimir-prod'
          serviceMap:
            datasourceUid: 'mimir-prod'
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'prod'

