apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-otel-instrumented-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: quay.io/falrayes/full-otel-instrumented-app-demo:prod-a9977901e0d32e2da4df897c0d3ff6816791fc54
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: OTEL_SERVICE_NAME
              value: "full-otel-instrumented-app-prod"

